#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = 

INC = -I.
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = -lz -lboost_filesystem -lboost_system -lv8container
LDFLAGS = 

V8CONTAINER_DIR_RELEASE = bin/Release

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -L$(V8CONTAINER_DIR_RELEASE)
LIB_RELEASE = $(LIB) 
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/v8unpack

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/V8File.o $(OBJDIR_RELEASE)/src/main.o
PREFIX=/usr
INSTALL_BIN=$(PREFIX)/bin
INSTALL_LIB=$(PREFIX)/lib

all: v8container release

v8container: 
	$(MAKE) --directory=v8container release

install:
	cp bin/Release/libv8container.so $(INSTALL_LIB)/libv8container.so
	cp bin/Release/v8unpack $(INSTALL_BIN)/v8unpack

uninstall:
	rm $(INSTALL_BIN)/v8unpack
	rm $(INSTALL_LIB)/libv8container.so

clean: clean_release

before_release: bin/Release

bin/Release:
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: $(OUT_RELEASE) after_release

$(OUT_RELEASE): bin/Release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE) -ldl

$(OBJDIR_RELEASE)/src/V8File.o: src/V8File.cpp
	$(CXX) -D__LINUX $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/V8File.cpp -o $(OBJDIR_RELEASE)/src/V8File.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) -D__LINUX $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_release after_release clean_release install uninstall v8container

